name: Deploy NestJS API to AWS with Terraform
run-name: ${{ github.actor }} is deploying to AWS with Terraform
on: [push]
env:
  AWS_REGION: us-east-1
  GH_TOKEN: ${{ secrets.FINE_GRAINED_TOKEN }}
jobs:
    Create-ECR:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
            - uses: hashicorp/setup-terraform@v1
              with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
                terraform_wrapper: false
            - run: terraform init
            - run: terraform plan -input=false -target=aws_ecr_repository.my-tf-images
            - run: terraform apply -target=aws_ecr_repository.my-tf-images -auto-approve -input=false
            - run: terraform output -raw ecr_repo_url | gh variable set ECR_URL
            - run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_URL }}
            - run: docker build -t ${{ vars.ECR_URL }} .
            - run: docker push ${{ vars.ECR_URL }}
            - run: terraform apply -auto-approve -input=false
            - name: Get EC2 ID'S
              id: get_ids
              run: |
                INSTANCE_ID1=$(terraform output -raw instance_1_ID)
                INSTANCE_ID2=$(terraform output -raw instance_2_ID)
                echo "::set-output name=instance_id1::$INSTANCE_ID1"
                echo "::set-output name=instance_id2::$INSTANCE_ID2"
            - name: Wait for EC2 instances to be running
              id: wait_for_ec2
              run: |
                INSTANCE_ID1=${{ steps.get_ids.outputs.instance_id1 }}
                INSTANCE_ID2=${{ steps.get_ids.outputs.instance_id2 }}
                echo "Waiting for EC2 instances $INSTANCE_ID1 and $INSTANCE_ID2 to be in 'running' state..."
                
                while true; do
                    STATE1=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID1 --query 'Reservations[0].Instances[0].State.Name' --output text)
                    STATE2=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID2 --query 'Reservations[0].Instances[0].State.Name' --output text)
                    echo "Instance $INSTANCE_ID1 state: $STATE1. Instance $INSTANCE_ID2 state: $STATE2."
                    
                    if [ "$STATE1" = "running" ] && [ "$STATE2" = "running" ]; then
                    echo "Both instances are running."
                    echo "::set-output name=instance_id1::$INSTANCE_ID1"
                    echo "::set-output name=instance_id2::$INSTANCE_ID2"
                    break
                    fi
                    sleep 10
                done
            - run: |
                INSTANCE_ID1=${{ steps.wait_for_ec2.outputs.instance_id1 }}
                INSTANCE_ID2=${{ steps.wait_for_ec2.outputs.instance_id2 }}
                $(aws ssm send-command --document-name="AWS-RunShellScript" --targets '[{"Key":"InstanceIds","Values":[$INSTANCE_ID1,$INSTANCE_ID2]}]' --parameters '{"commands":["#!/bin/bash","sudo yum install docker -y","sudo service docker start","sudo docker pull ${{ vars.ECR_URL }}","sudo docker run -dp 80:3000 --name server ${{ vars.ECR_URL }}"]}')